// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package PlainTransport

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__Transport "github.com/jiyeyuran/mediasoup-go/v2/internal/FBS/Transport"
)

type TupleNotificationT struct {
	Tuple *FBS__Transport.TupleT `json:"tuple"`
}

func (t *TupleNotificationT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tupleOffset := t.Tuple.Pack(builder)
	TupleNotificationStart(builder)
	TupleNotificationAddTuple(builder, tupleOffset)
	return TupleNotificationEnd(builder)
}

func (rcv *TupleNotification) UnPackTo(t *TupleNotificationT) {
	t.Tuple = rcv.Tuple(nil).UnPack()
}

func (rcv *TupleNotification) UnPack() *TupleNotificationT {
	if rcv == nil {
		return nil
	}
	t := &TupleNotificationT{}
	rcv.UnPackTo(t)
	return t
}

type TupleNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsTupleNotification(buf []byte, offset flatbuffers.UOffsetT) *TupleNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TupleNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishTupleNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTupleNotification(buf []byte, offset flatbuffers.UOffsetT) *TupleNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TupleNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTupleNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TupleNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TupleNotification) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TupleNotification) Tuple(obj *FBS__Transport.Tuple) *FBS__Transport.Tuple {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__Transport.Tuple)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TupleNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TupleNotificationAddTuple(builder *flatbuffers.Builder, tuple flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tuple), 0)
}
func TupleNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
