// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Consumer

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__RtpParameters "github.com/jiyeyuran/mediasoup-go/v2/internal/FBS/RtpParameters"
)

type BaseConsumerDumpT struct {
	Id string `json:"id"`
	Type FBS__RtpParameters.Type `json:"type"`
	ProducerId string `json:"producer_id"`
	Kind FBS__RtpParameters.MediaKind `json:"kind"`
	RtpParameters *FBS__RtpParameters.RtpParametersT `json:"rtp_parameters"`
	ConsumableRtpEncodings []*FBS__RtpParameters.RtpEncodingParametersT `json:"consumable_rtp_encodings"`
	SupportedCodecPayloadTypes []byte `json:"supported_codec_payload_types"`
	TraceEventTypes []TraceEventType `json:"trace_event_types"`
	Paused bool `json:"paused"`
	ProducerPaused bool `json:"producer_paused"`
	Priority byte `json:"priority"`
}

func (t *BaseConsumerDumpT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	producerIdOffset := flatbuffers.UOffsetT(0)
	if t.ProducerId != "" {
		producerIdOffset = builder.CreateString(t.ProducerId)
	}
	rtpParametersOffset := t.RtpParameters.Pack(builder)
	consumableRtpEncodingsOffset := flatbuffers.UOffsetT(0)
	if t.ConsumableRtpEncodings != nil {
		consumableRtpEncodingsLength := len(t.ConsumableRtpEncodings)
		consumableRtpEncodingsOffsets := make([]flatbuffers.UOffsetT, consumableRtpEncodingsLength)
		for j := 0; j < consumableRtpEncodingsLength; j++ {
			consumableRtpEncodingsOffsets[j] = t.ConsumableRtpEncodings[j].Pack(builder)
		}
		BaseConsumerDumpStartConsumableRtpEncodingsVector(builder, consumableRtpEncodingsLength)
		for j := consumableRtpEncodingsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(consumableRtpEncodingsOffsets[j])
		}
		consumableRtpEncodingsOffset = builder.EndVector(consumableRtpEncodingsLength)
	}
	supportedCodecPayloadTypesOffset := flatbuffers.UOffsetT(0)
	if t.SupportedCodecPayloadTypes != nil {
		supportedCodecPayloadTypesOffset = builder.CreateByteString(t.SupportedCodecPayloadTypes)
	}
	traceEventTypesOffset := flatbuffers.UOffsetT(0)
	if t.TraceEventTypes != nil {
		traceEventTypesLength := len(t.TraceEventTypes)
		BaseConsumerDumpStartTraceEventTypesVector(builder, traceEventTypesLength)
		for j := traceEventTypesLength - 1; j >= 0; j-- {
			builder.PrependByte(byte(t.TraceEventTypes[j]))
		}
		traceEventTypesOffset = builder.EndVector(traceEventTypesLength)
	}
	BaseConsumerDumpStart(builder)
	BaseConsumerDumpAddId(builder, idOffset)
	BaseConsumerDumpAddType(builder, t.Type)
	BaseConsumerDumpAddProducerId(builder, producerIdOffset)
	BaseConsumerDumpAddKind(builder, t.Kind)
	BaseConsumerDumpAddRtpParameters(builder, rtpParametersOffset)
	BaseConsumerDumpAddConsumableRtpEncodings(builder, consumableRtpEncodingsOffset)
	BaseConsumerDumpAddSupportedCodecPayloadTypes(builder, supportedCodecPayloadTypesOffset)
	BaseConsumerDumpAddTraceEventTypes(builder, traceEventTypesOffset)
	BaseConsumerDumpAddPaused(builder, t.Paused)
	BaseConsumerDumpAddProducerPaused(builder, t.ProducerPaused)
	BaseConsumerDumpAddPriority(builder, t.Priority)
	return BaseConsumerDumpEnd(builder)
}

func (rcv *BaseConsumerDump) UnPackTo(t *BaseConsumerDumpT) {
	t.Id = string(rcv.Id())
	t.Type = rcv.Type()
	t.ProducerId = string(rcv.ProducerId())
	t.Kind = rcv.Kind()
	t.RtpParameters = rcv.RtpParameters(nil).UnPack()
	consumableRtpEncodingsLength := rcv.ConsumableRtpEncodingsLength()
	t.ConsumableRtpEncodings = make([]*FBS__RtpParameters.RtpEncodingParametersT, consumableRtpEncodingsLength)
	for j := 0; j < consumableRtpEncodingsLength; j++ {
		x := FBS__RtpParameters.RtpEncodingParameters{}
		rcv.ConsumableRtpEncodings(&x, j)
		t.ConsumableRtpEncodings[j] = x.UnPack()
	}
	t.SupportedCodecPayloadTypes = rcv.SupportedCodecPayloadTypesBytes()
	traceEventTypesLength := rcv.TraceEventTypesLength()
	t.TraceEventTypes = make([]TraceEventType, traceEventTypesLength)
	for j := 0; j < traceEventTypesLength; j++ {
		t.TraceEventTypes[j] = rcv.TraceEventTypes(j)
	}
	t.Paused = rcv.Paused()
	t.ProducerPaused = rcv.ProducerPaused()
	t.Priority = rcv.Priority()
}

func (rcv *BaseConsumerDump) UnPack() *BaseConsumerDumpT {
	if rcv == nil {
		return nil
	}
	t := &BaseConsumerDumpT{}
	rcv.UnPackTo(t)
	return t
}

type BaseConsumerDump struct {
	_tab flatbuffers.Table
}

func GetRootAsBaseConsumerDump(buf []byte, offset flatbuffers.UOffsetT) *BaseConsumerDump {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BaseConsumerDump{}
	x.Init(buf, n+offset)
	return x
}

func FinishBaseConsumerDumpBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBaseConsumerDump(buf []byte, offset flatbuffers.UOffsetT) *BaseConsumerDump {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BaseConsumerDump{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBaseConsumerDumpBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BaseConsumerDump) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BaseConsumerDump) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BaseConsumerDump) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BaseConsumerDump) Type() FBS__RtpParameters.Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return FBS__RtpParameters.Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *BaseConsumerDump) MutateType(n FBS__RtpParameters.Type) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *BaseConsumerDump) ProducerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BaseConsumerDump) Kind() FBS__RtpParameters.MediaKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return FBS__RtpParameters.MediaKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *BaseConsumerDump) MutateKind(n FBS__RtpParameters.MediaKind) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *BaseConsumerDump) RtpParameters(obj *FBS__RtpParameters.RtpParameters) *FBS__RtpParameters.RtpParameters {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__RtpParameters.RtpParameters)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BaseConsumerDump) ConsumableRtpEncodings(obj *FBS__RtpParameters.RtpEncodingParameters, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BaseConsumerDump) ConsumableRtpEncodingsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BaseConsumerDump) SupportedCodecPayloadTypes(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BaseConsumerDump) SupportedCodecPayloadTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BaseConsumerDump) SupportedCodecPayloadTypesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BaseConsumerDump) MutateSupportedCodecPayloadTypes(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BaseConsumerDump) TraceEventTypes(j int) TraceEventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return TraceEventType(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *BaseConsumerDump) TraceEventTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BaseConsumerDump) TraceEventTypesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BaseConsumerDump) MutateTraceEventTypes(j int, n TraceEventType) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *BaseConsumerDump) Paused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BaseConsumerDump) MutatePaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *BaseConsumerDump) ProducerPaused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BaseConsumerDump) MutateProducerPaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *BaseConsumerDump) Priority() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BaseConsumerDump) MutatePriority(n byte) bool {
	return rcv._tab.MutateByteSlot(24, n)
}

func BaseConsumerDumpStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func BaseConsumerDumpAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func BaseConsumerDumpAddType(builder *flatbuffers.Builder, type_ FBS__RtpParameters.Type) {
	builder.PrependByteSlot(1, byte(type_), 0)
}
func BaseConsumerDumpAddProducerId(builder *flatbuffers.Builder, producerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(producerId), 0)
}
func BaseConsumerDumpAddKind(builder *flatbuffers.Builder, kind FBS__RtpParameters.MediaKind) {
	builder.PrependByteSlot(3, byte(kind), 0)
}
func BaseConsumerDumpAddRtpParameters(builder *flatbuffers.Builder, rtpParameters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(rtpParameters), 0)
}
func BaseConsumerDumpAddConsumableRtpEncodings(builder *flatbuffers.Builder, consumableRtpEncodings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(consumableRtpEncodings), 0)
}
func BaseConsumerDumpStartConsumableRtpEncodingsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BaseConsumerDumpAddSupportedCodecPayloadTypes(builder *flatbuffers.Builder, supportedCodecPayloadTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(supportedCodecPayloadTypes), 0)
}
func BaseConsumerDumpStartSupportedCodecPayloadTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BaseConsumerDumpAddTraceEventTypes(builder *flatbuffers.Builder, traceEventTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(traceEventTypes), 0)
}
func BaseConsumerDumpStartTraceEventTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BaseConsumerDumpAddPaused(builder *flatbuffers.Builder, paused bool) {
	builder.PrependBoolSlot(8, paused, false)
}
func BaseConsumerDumpAddProducerPaused(builder *flatbuffers.Builder, producerPaused bool) {
	builder.PrependBoolSlot(9, producerPaused, false)
}
func BaseConsumerDumpAddPriority(builder *flatbuffers.Builder, priority byte) {
	builder.PrependByteSlot(10, priority, 0)
}
func BaseConsumerDumpEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
