// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConnectRequestT struct {
	DtlsParameters *DtlsParametersT `json:"dtls_parameters"`
}

func (t *ConnectRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	dtlsParametersOffset := t.DtlsParameters.Pack(builder)
	ConnectRequestStart(builder)
	ConnectRequestAddDtlsParameters(builder, dtlsParametersOffset)
	return ConnectRequestEnd(builder)
}

func (rcv *ConnectRequest) UnPackTo(t *ConnectRequestT) {
	t.DtlsParameters = rcv.DtlsParameters(nil).UnPack()
}

func (rcv *ConnectRequest) UnPack() *ConnectRequestT {
	if rcv == nil {
		return nil
	}
	t := &ConnectRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ConnectRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConnectRequest(buf []byte, offset flatbuffers.UOffsetT) *ConnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConnectRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishConnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConnectRequest(buf []byte, offset flatbuffers.UOffsetT) *ConnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConnectRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConnectRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConnectRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConnectRequest) DtlsParameters(obj *DtlsParameters) *DtlsParameters {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DtlsParameters)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ConnectRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConnectRequestAddDtlsParameters(builder *flatbuffers.Builder, dtlsParameters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dtlsParameters), 0)
}
func ConnectRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
