// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import "strconv"

type DtlsState byte

const (
	DtlsStateNEW        DtlsState = 0
	DtlsStateCONNECTING DtlsState = 1
	DtlsStateCONNECTED  DtlsState = 2
	DtlsStateFAILED     DtlsState = 3
	DtlsStateCLOSED     DtlsState = 4
)

var EnumNamesDtlsState = map[DtlsState]string{
	DtlsStateNEW:        "NEW",
	DtlsStateCONNECTING: "CONNECTING",
	DtlsStateCONNECTED:  "CONNECTED",
	DtlsStateFAILED:     "FAILED",
	DtlsStateCLOSED:     "CLOSED",
}

var EnumValuesDtlsState = map[string]DtlsState{
	"NEW":        DtlsStateNEW,
	"CONNECTING": DtlsStateCONNECTING,
	"CONNECTED":  DtlsStateCONNECTED,
	"FAILED":     DtlsStateFAILED,
	"CLOSED":     DtlsStateCLOSED,
}

func (v DtlsState) String() string {
	if s, ok := EnumNamesDtlsState[v]; ok {
		return s
	}
	return "DtlsState(" + strconv.FormatInt(int64(v), 10) + ")"
}
