// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import "strconv"

type FingerprintAlgorithm byte

const (
	FingerprintAlgorithmSHA1   FingerprintAlgorithm = 0
	FingerprintAlgorithmSHA224 FingerprintAlgorithm = 1
	FingerprintAlgorithmSHA256 FingerprintAlgorithm = 2
	FingerprintAlgorithmSHA384 FingerprintAlgorithm = 3
	FingerprintAlgorithmSHA512 FingerprintAlgorithm = 4
)

var EnumNamesFingerprintAlgorithm = map[FingerprintAlgorithm]string{
	FingerprintAlgorithmSHA1:   "SHA1",
	FingerprintAlgorithmSHA224: "SHA224",
	FingerprintAlgorithmSHA256: "SHA256",
	FingerprintAlgorithmSHA384: "SHA384",
	FingerprintAlgorithmSHA512: "SHA512",
}

var EnumValuesFingerprintAlgorithm = map[string]FingerprintAlgorithm{
	"SHA1":   FingerprintAlgorithmSHA1,
	"SHA224": FingerprintAlgorithmSHA224,
	"SHA256": FingerprintAlgorithmSHA256,
	"SHA384": FingerprintAlgorithmSHA384,
	"SHA512": FingerprintAlgorithmSHA512,
}

func (v FingerprintAlgorithm) String() string {
	if s, ok := EnumNamesFingerprintAlgorithm[v]; ok {
		return s
	}
	return "FingerprintAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
