// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import "strconv"

type IceRole byte

const (
	IceRoleCONTROLLED  IceRole = 0
	IceRoleCONTROLLING IceRole = 1
)

var EnumNamesIceRole = map[IceRole]string{
	IceRoleCONTROLLED:  "CONTROLLED",
	IceRoleCONTROLLING: "CONTROLLING",
}

var EnumValuesIceRole = map[string]IceRole{
	"CONTROLLED":  IceRoleCONTROLLED,
	"CONTROLLING": IceRoleCONTROLLING,
}

func (v IceRole) String() string {
	if s, ok := EnumNamesIceRole[v]; ok {
		return s
	}
	return "IceRole(" + strconv.FormatInt(int64(v), 10) + ")"
}
