// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConsumerRtpMappingT struct {
	Codecs []*ConsumerCodecMappingT `json:"codecs"`
	HeaderExtensions []*ConsumerHeaderExtensionMappingT `json:"header_extensions"`
}

func (t *ConsumerRtpMappingT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	codecsOffset := flatbuffers.UOffsetT(0)
	if t.Codecs != nil {
		codecsLength := len(t.Codecs)
		codecsOffsets := make([]flatbuffers.UOffsetT, codecsLength)
		for j := 0; j < codecsLength; j++ {
			codecsOffsets[j] = t.Codecs[j].Pack(builder)
		}
		ConsumerRtpMappingStartCodecsVector(builder, codecsLength)
		for j := codecsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(codecsOffsets[j])
		}
		codecsOffset = builder.EndVector(codecsLength)
	}
	headerExtensionsOffset := flatbuffers.UOffsetT(0)
	if t.HeaderExtensions != nil {
		headerExtensionsLength := len(t.HeaderExtensions)
		headerExtensionsOffsets := make([]flatbuffers.UOffsetT, headerExtensionsLength)
		for j := 0; j < headerExtensionsLength; j++ {
			headerExtensionsOffsets[j] = t.HeaderExtensions[j].Pack(builder)
		}
		ConsumerRtpMappingStartHeaderExtensionsVector(builder, headerExtensionsLength)
		for j := headerExtensionsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(headerExtensionsOffsets[j])
		}
		headerExtensionsOffset = builder.EndVector(headerExtensionsLength)
	}
	ConsumerRtpMappingStart(builder)
	ConsumerRtpMappingAddCodecs(builder, codecsOffset)
	ConsumerRtpMappingAddHeaderExtensions(builder, headerExtensionsOffset)
	return ConsumerRtpMappingEnd(builder)
}

func (rcv *ConsumerRtpMapping) UnPackTo(t *ConsumerRtpMappingT) {
	codecsLength := rcv.CodecsLength()
	t.Codecs = make([]*ConsumerCodecMappingT, codecsLength)
	for j := 0; j < codecsLength; j++ {
		x := ConsumerCodecMapping{}
		rcv.Codecs(&x, j)
		t.Codecs[j] = x.UnPack()
	}
	headerExtensionsLength := rcv.HeaderExtensionsLength()
	t.HeaderExtensions = make([]*ConsumerHeaderExtensionMappingT, headerExtensionsLength)
	for j := 0; j < headerExtensionsLength; j++ {
		x := ConsumerHeaderExtensionMapping{}
		rcv.HeaderExtensions(&x, j)
		t.HeaderExtensions[j] = x.UnPack()
	}
}

func (rcv *ConsumerRtpMapping) UnPack() *ConsumerRtpMappingT {
	if rcv == nil {
		return nil
	}
	t := &ConsumerRtpMappingT{}
	rcv.UnPackTo(t)
	return t
}

type ConsumerRtpMapping struct {
	_tab flatbuffers.Table
}

func GetRootAsConsumerRtpMapping(buf []byte, offset flatbuffers.UOffsetT) *ConsumerRtpMapping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsumerRtpMapping{}
	x.Init(buf, n+offset)
	return x
}

func FinishConsumerRtpMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConsumerRtpMapping(buf []byte, offset flatbuffers.UOffsetT) *ConsumerRtpMapping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsumerRtpMapping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConsumerRtpMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConsumerRtpMapping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsumerRtpMapping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsumerRtpMapping) Codecs(obj *ConsumerCodecMapping, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ConsumerRtpMapping) CodecsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsumerRtpMapping) HeaderExtensions(obj *ConsumerHeaderExtensionMapping, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ConsumerRtpMapping) HeaderExtensionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ConsumerRtpMappingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConsumerRtpMappingAddCodecs(builder *flatbuffers.Builder, codecs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(codecs), 0)
}
func ConsumerRtpMappingStartCodecsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConsumerRtpMappingAddHeaderExtensions(builder *flatbuffers.Builder, headerExtensions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(headerExtensions), 0)
}
func ConsumerRtpMappingStartHeaderExtensionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConsumerRtpMappingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
