// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConsumerCodecMappingT struct {
	ProducerPayloadType byte `json:"producer_payload_type"`
	ConsumerPayloadType byte `json:"consumer_payload_type"`
}

func (t *ConsumerCodecMappingT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	ConsumerCodecMappingStart(builder)
	ConsumerCodecMappingAddProducerPayloadType(builder, t.ProducerPayloadType)
	ConsumerCodecMappingAddConsumerPayloadType(builder, t.ConsumerPayloadType)
	return ConsumerCodecMappingEnd(builder)
}

func (rcv *ConsumerCodecMapping) UnPackTo(t *ConsumerCodecMappingT) {
	t.ProducerPayloadType = rcv.ProducerPayloadType()
	t.ConsumerPayloadType = rcv.ConsumerPayloadType()
}

func (rcv *ConsumerCodecMapping) UnPack() *ConsumerCodecMappingT {
	if rcv == nil {
		return nil
	}
	t := &ConsumerCodecMappingT{}
	rcv.UnPackTo(t)
	return t
}

type ConsumerCodecMapping struct {
	_tab flatbuffers.Table
}

func GetRootAsConsumerCodecMapping(buf []byte, offset flatbuffers.UOffsetT) *ConsumerCodecMapping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsumerCodecMapping{}
	x.Init(buf, n+offset)
	return x
}

func FinishConsumerCodecMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConsumerCodecMapping(buf []byte, offset flatbuffers.UOffsetT) *ConsumerCodecMapping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsumerCodecMapping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConsumerCodecMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConsumerCodecMapping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsumerCodecMapping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsumerCodecMapping) ProducerPayloadType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsumerCodecMapping) MutateProducerPayloadType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ConsumerCodecMapping) ConsumerPayloadType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsumerCodecMapping) MutateConsumerPayloadType(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func ConsumerCodecMappingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConsumerCodecMappingAddProducerPayloadType(builder *flatbuffers.Builder, producerPayloadType byte) {
	builder.PrependByteSlot(0, producerPayloadType, 0)
}
func ConsumerCodecMappingAddConsumerPayloadType(builder *flatbuffers.Builder, consumerPayloadType byte) {
	builder.PrependByteSlot(1, consumerPayloadType, 0)
}
func ConsumerCodecMappingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
