// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Integer32T struct {
	Value int32 `json:"value"`
}

func (t *Integer32T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	Integer32Start(builder)
	Integer32AddValue(builder, t.Value)
	return Integer32End(builder)
}

func (rcv *Integer32) UnPackTo(t *Integer32T) {
	t.Value = rcv.Value()
}

func (rcv *Integer32) UnPack() *Integer32T {
	if rcv == nil {
		return nil
	}
	t := &Integer32T{}
	rcv.UnPackTo(t)
	return t
}

type Integer32 struct {
	_tab flatbuffers.Table
}

func GetRootAsInteger32(buf []byte, offset flatbuffers.UOffsetT) *Integer32 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Integer32{}
	x.Init(buf, n+offset)
	return x
}

func FinishInteger32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInteger32(buf []byte, offset flatbuffers.UOffsetT) *Integer32 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Integer32{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInteger32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Integer32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Integer32) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Integer32) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Integer32) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func Integer32Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Integer32AddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(0, value, 0)
}
func Integer32End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
