// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import "strconv"

type RtpHeaderExtensionUri byte

const (
	RtpHeaderExtensionUriMid                    RtpHeaderExtensionUri = 0
	RtpHeaderExtensionUriRtpStreamId            RtpHeaderExtensionUri = 1
	RtpHeaderExtensionUriRepairRtpStreamId      RtpHeaderExtensionUri = 2
	RtpHeaderExtensionUriAbsSendTime            RtpHeaderExtensionUri = 3
	RtpHeaderExtensionUriTransportWideCcDraft01 RtpHeaderExtensionUri = 4
	RtpHeaderExtensionUriSsrcAudioLevel         RtpHeaderExtensionUri = 5
	RtpHeaderExtensionUriDependencyDescriptor   RtpHeaderExtensionUri = 6
	RtpHeaderExtensionUriVideoOrientation       RtpHeaderExtensionUri = 7
	RtpHeaderExtensionUriTimeOffset             RtpHeaderExtensionUri = 8
	RtpHeaderExtensionUriAbsCaptureTime         RtpHeaderExtensionUri = 9
	RtpHeaderExtensionUriPlayoutDelay           RtpHeaderExtensionUri = 10
	RtpHeaderExtensionUriMediasoupPacketId      RtpHeaderExtensionUri = 11
)

var EnumNamesRtpHeaderExtensionUri = map[RtpHeaderExtensionUri]string{
	RtpHeaderExtensionUriMid:                    "Mid",
	RtpHeaderExtensionUriRtpStreamId:            "RtpStreamId",
	RtpHeaderExtensionUriRepairRtpStreamId:      "RepairRtpStreamId",
	RtpHeaderExtensionUriAbsSendTime:            "AbsSendTime",
	RtpHeaderExtensionUriTransportWideCcDraft01: "TransportWideCcDraft01",
	RtpHeaderExtensionUriSsrcAudioLevel:         "SsrcAudioLevel",
	RtpHeaderExtensionUriDependencyDescriptor:   "DependencyDescriptor",
	RtpHeaderExtensionUriVideoOrientation:       "VideoOrientation",
	RtpHeaderExtensionUriTimeOffset:             "TimeOffset",
	RtpHeaderExtensionUriAbsCaptureTime:         "AbsCaptureTime",
	RtpHeaderExtensionUriPlayoutDelay:           "PlayoutDelay",
	RtpHeaderExtensionUriMediasoupPacketId:      "MediasoupPacketId",
}

var EnumValuesRtpHeaderExtensionUri = map[string]RtpHeaderExtensionUri{
	"Mid":                    RtpHeaderExtensionUriMid,
	"RtpStreamId":            RtpHeaderExtensionUriRtpStreamId,
	"RepairRtpStreamId":      RtpHeaderExtensionUriRepairRtpStreamId,
	"AbsSendTime":            RtpHeaderExtensionUriAbsSendTime,
	"TransportWideCcDraft01": RtpHeaderExtensionUriTransportWideCcDraft01,
	"SsrcAudioLevel":         RtpHeaderExtensionUriSsrcAudioLevel,
	"DependencyDescriptor":   RtpHeaderExtensionUriDependencyDescriptor,
	"VideoOrientation":       RtpHeaderExtensionUriVideoOrientation,
	"TimeOffset":             RtpHeaderExtensionUriTimeOffset,
	"AbsCaptureTime":         RtpHeaderExtensionUriAbsCaptureTime,
	"PlayoutDelay":           RtpHeaderExtensionUriPlayoutDelay,
	"MediasoupPacketId":      RtpHeaderExtensionUriMediasoupPacketId,
}

func (v RtpHeaderExtensionUri) String() string {
	if s, ok := EnumNamesRtpHeaderExtensionUri[v]; ok {
		return s
	}
	return "RtpHeaderExtensionUri(" + strconv.FormatInt(int64(v), 10) + ")"
}
