// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import "strconv"

type Type byte

const (
	TypeSIMPLE    Type = 0
	TypeSIMULCAST Type = 1
	TypeSVC       Type = 2
	TypePIPE      Type = 3
)

var EnumNamesType = map[Type]string{
	TypeSIMPLE:    "SIMPLE",
	TypeSIMULCAST: "SIMULCAST",
	TypeSVC:       "SVC",
	TypePIPE:      "PIPE",
}

var EnumValuesType = map[string]Type{
	"SIMPLE":    TypeSIMPLE,
	"SIMULCAST": TypeSIMULCAST,
	"SVC":       TypeSVC,
	"PIPE":      TypePIPE,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
