// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DataConsumer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendRequestT struct {
	Ppid uint32 `json:"ppid"`
	Data []byte `json:"data"`
}

func (t *SendRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	SendRequestStart(builder)
	SendRequestAddPpid(builder, t.Ppid)
	SendRequestAddData(builder, dataOffset)
	return SendRequestEnd(builder)
}

func (rcv *SendRequest) UnPackTo(t *SendRequestT) {
	t.Ppid = rcv.Ppid()
	t.Data = rcv.DataBytes()
}

func (rcv *SendRequest) UnPack() *SendRequestT {
	if rcv == nil {
		return nil
	}
	t := &SendRequestT{}
	rcv.UnPackTo(t)
	return t
}

type SendRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSendRequest(buf []byte, offset flatbuffers.UOffsetT) *SendRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSendRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSendRequest(buf []byte, offset flatbuffers.UOffsetT) *SendRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSendRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SendRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendRequest) Ppid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendRequest) MutatePpid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SendRequest) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SendRequest) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SendRequest) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SendRequest) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SendRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SendRequestAddPpid(builder *flatbuffers.Builder, ppid uint32) {
	builder.PrependUint32Slot(0, ppid, 0)
}
func SendRequestAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func SendRequestStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SendRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
