// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Producer

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__RtpParameters "github.com/jiyeyuran/mediasoup-go/v2/internal/FBS/RtpParameters"
	FBS__RtpStream "github.com/jiyeyuran/mediasoup-go/v2/internal/FBS/RtpStream"
)

type DumpResponseT struct {
	Id string `json:"id"`
	Kind FBS__RtpParameters.MediaKind `json:"kind"`
	Type FBS__RtpParameters.Type `json:"type"`
	RtpParameters *FBS__RtpParameters.RtpParametersT `json:"rtp_parameters"`
	RtpMapping *FBS__RtpParameters.RtpMappingT `json:"rtp_mapping"`
	RtpStreams []*FBS__RtpStream.DumpT `json:"rtp_streams"`
	TraceEventTypes []TraceEventType `json:"trace_event_types"`
	Paused bool `json:"paused"`
}

func (t *DumpResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	rtpParametersOffset := t.RtpParameters.Pack(builder)
	rtpMappingOffset := t.RtpMapping.Pack(builder)
	rtpStreamsOffset := flatbuffers.UOffsetT(0)
	if t.RtpStreams != nil {
		rtpStreamsLength := len(t.RtpStreams)
		rtpStreamsOffsets := make([]flatbuffers.UOffsetT, rtpStreamsLength)
		for j := 0; j < rtpStreamsLength; j++ {
			rtpStreamsOffsets[j] = t.RtpStreams[j].Pack(builder)
		}
		DumpResponseStartRtpStreamsVector(builder, rtpStreamsLength)
		for j := rtpStreamsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(rtpStreamsOffsets[j])
		}
		rtpStreamsOffset = builder.EndVector(rtpStreamsLength)
	}
	traceEventTypesOffset := flatbuffers.UOffsetT(0)
	if t.TraceEventTypes != nil {
		traceEventTypesLength := len(t.TraceEventTypes)
		DumpResponseStartTraceEventTypesVector(builder, traceEventTypesLength)
		for j := traceEventTypesLength - 1; j >= 0; j-- {
			builder.PrependByte(byte(t.TraceEventTypes[j]))
		}
		traceEventTypesOffset = builder.EndVector(traceEventTypesLength)
	}
	DumpResponseStart(builder)
	DumpResponseAddId(builder, idOffset)
	DumpResponseAddKind(builder, t.Kind)
	DumpResponseAddType(builder, t.Type)
	DumpResponseAddRtpParameters(builder, rtpParametersOffset)
	DumpResponseAddRtpMapping(builder, rtpMappingOffset)
	DumpResponseAddRtpStreams(builder, rtpStreamsOffset)
	DumpResponseAddTraceEventTypes(builder, traceEventTypesOffset)
	DumpResponseAddPaused(builder, t.Paused)
	return DumpResponseEnd(builder)
}

func (rcv *DumpResponse) UnPackTo(t *DumpResponseT) {
	t.Id = string(rcv.Id())
	t.Kind = rcv.Kind()
	t.Type = rcv.Type()
	t.RtpParameters = rcv.RtpParameters(nil).UnPack()
	t.RtpMapping = rcv.RtpMapping(nil).UnPack()
	rtpStreamsLength := rcv.RtpStreamsLength()
	t.RtpStreams = make([]*FBS__RtpStream.DumpT, rtpStreamsLength)
	for j := 0; j < rtpStreamsLength; j++ {
		x := FBS__RtpStream.Dump{}
		rcv.RtpStreams(&x, j)
		t.RtpStreams[j] = x.UnPack()
	}
	traceEventTypesLength := rcv.TraceEventTypesLength()
	t.TraceEventTypes = make([]TraceEventType, traceEventTypesLength)
	for j := 0; j < traceEventTypesLength; j++ {
		t.TraceEventTypes[j] = rcv.TraceEventTypes(j)
	}
	t.Paused = rcv.Paused()
}

func (rcv *DumpResponse) UnPack() *DumpResponseT {
	if rcv == nil {
		return nil
	}
	t := &DumpResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DumpResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDumpResponse(buf []byte, offset flatbuffers.UOffsetT) *DumpResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DumpResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishDumpResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDumpResponse(buf []byte, offset flatbuffers.UOffsetT) *DumpResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DumpResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDumpResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DumpResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DumpResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DumpResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DumpResponse) Kind() FBS__RtpParameters.MediaKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return FBS__RtpParameters.MediaKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DumpResponse) MutateKind(n FBS__RtpParameters.MediaKind) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *DumpResponse) Type() FBS__RtpParameters.Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return FBS__RtpParameters.Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DumpResponse) MutateType(n FBS__RtpParameters.Type) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *DumpResponse) RtpParameters(obj *FBS__RtpParameters.RtpParameters) *FBS__RtpParameters.RtpParameters {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__RtpParameters.RtpParameters)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DumpResponse) RtpMapping(obj *FBS__RtpParameters.RtpMapping) *FBS__RtpParameters.RtpMapping {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__RtpParameters.RtpMapping)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DumpResponse) RtpStreams(obj *FBS__RtpStream.Dump, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DumpResponse) RtpStreamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DumpResponse) TraceEventTypes(j int) TraceEventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return TraceEventType(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *DumpResponse) TraceEventTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DumpResponse) TraceEventTypesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DumpResponse) MutateTraceEventTypes(j int, n TraceEventType) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *DumpResponse) Paused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DumpResponse) MutatePaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func DumpResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func DumpResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DumpResponseAddKind(builder *flatbuffers.Builder, kind FBS__RtpParameters.MediaKind) {
	builder.PrependByteSlot(1, byte(kind), 0)
}
func DumpResponseAddType(builder *flatbuffers.Builder, type_ FBS__RtpParameters.Type) {
	builder.PrependByteSlot(2, byte(type_), 0)
}
func DumpResponseAddRtpParameters(builder *flatbuffers.Builder, rtpParameters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(rtpParameters), 0)
}
func DumpResponseAddRtpMapping(builder *flatbuffers.Builder, rtpMapping flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(rtpMapping), 0)
}
func DumpResponseAddRtpStreams(builder *flatbuffers.Builder, rtpStreams flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(rtpStreams), 0)
}
func DumpResponseStartRtpStreamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DumpResponseAddTraceEventTypes(builder *flatbuffers.Builder, traceEventTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(traceEventTypes), 0)
}
func DumpResponseStartTraceEventTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DumpResponseAddPaused(builder *flatbuffers.Builder, paused bool) {
	builder.PrependBoolSlot(7, paused, false)
}
func DumpResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
