// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Producer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FirTraceInfoT struct {
	Ssrc uint32 `json:"ssrc"`
}

func (t *FirTraceInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FirTraceInfoStart(builder)
	FirTraceInfoAddSsrc(builder, t.Ssrc)
	return FirTraceInfoEnd(builder)
}

func (rcv *FirTraceInfo) UnPackTo(t *FirTraceInfoT) {
	t.Ssrc = rcv.Ssrc()
}

func (rcv *FirTraceInfo) UnPack() *FirTraceInfoT {
	if rcv == nil {
		return nil
	}
	t := &FirTraceInfoT{}
	rcv.UnPackTo(t)
	return t
}

type FirTraceInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsFirTraceInfo(buf []byte, offset flatbuffers.UOffsetT) *FirTraceInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FirTraceInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishFirTraceInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFirTraceInfo(buf []byte, offset flatbuffers.UOffsetT) *FirTraceInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FirTraceInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFirTraceInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FirTraceInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FirTraceInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FirTraceInfo) Ssrc() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FirTraceInfo) MutateSsrc(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func FirTraceInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FirTraceInfoAddSsrc(builder *flatbuffers.Builder, ssrc uint32) {
	builder.PrependUint32Slot(0, ssrc, 0)
}
func FirTraceInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
