// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DirectTransport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtcpNotificationT struct {
	Data []byte `json:"data"`
}

func (t *RtcpNotificationT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	RtcpNotificationStart(builder)
	RtcpNotificationAddData(builder, dataOffset)
	return RtcpNotificationEnd(builder)
}

func (rcv *RtcpNotification) UnPackTo(t *RtcpNotificationT) {
	t.Data = rcv.DataBytes()
}

func (rcv *RtcpNotification) UnPack() *RtcpNotificationT {
	if rcv == nil {
		return nil
	}
	t := &RtcpNotificationT{}
	rcv.UnPackTo(t)
	return t
}

type RtcpNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsRtcpNotification(buf []byte, offset flatbuffers.UOffsetT) *RtcpNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtcpNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtcpNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtcpNotification(buf []byte, offset flatbuffers.UOffsetT) *RtcpNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtcpNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtcpNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtcpNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtcpNotification) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtcpNotification) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RtcpNotification) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RtcpNotification) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RtcpNotification) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func RtcpNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RtcpNotificationAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func RtcpNotificationStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RtcpNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
