// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CloseDataProducerRequestT struct {
	DataProducerId string `json:"data_producer_id"`
}

func (t *CloseDataProducerRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	dataProducerIdOffset := flatbuffers.UOffsetT(0)
	if t.DataProducerId != "" {
		dataProducerIdOffset = builder.CreateString(t.DataProducerId)
	}
	CloseDataProducerRequestStart(builder)
	CloseDataProducerRequestAddDataProducerId(builder, dataProducerIdOffset)
	return CloseDataProducerRequestEnd(builder)
}

func (rcv *CloseDataProducerRequest) UnPackTo(t *CloseDataProducerRequestT) {
	t.DataProducerId = string(rcv.DataProducerId())
}

func (rcv *CloseDataProducerRequest) UnPack() *CloseDataProducerRequestT {
	if rcv == nil {
		return nil
	}
	t := &CloseDataProducerRequestT{}
	rcv.UnPackTo(t)
	return t
}

type CloseDataProducerRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCloseDataProducerRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseDataProducerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CloseDataProducerRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCloseDataProducerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCloseDataProducerRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseDataProducerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CloseDataProducerRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCloseDataProducerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CloseDataProducerRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CloseDataProducerRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CloseDataProducerRequest) DataProducerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CloseDataProducerRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CloseDataProducerRequestAddDataProducerId(builder *flatbuffers.Builder, dataProducerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataProducerId), 0)
}
func CloseDataProducerRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
