// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OptionsT struct {
	Direct bool `json:"direct"`
	InitialAvailableOutgoingBitrate *uint32 `json:"initial_available_outgoing_bitrate"`
	EnableSctp bool `json:"enable_sctp"`
	MaxSendMessageSize uint32 `json:"max_send_message_size"`
	MaxReceiveMessageSize uint32 `json:"max_receive_message_size"`
	SctpSendBufferSize uint32 `json:"sctp_send_buffer_size"`
	SctpPerStreamSendQueueLimit uint32 `json:"sctp_per_stream_send_queue_limit"`
	SctpMaxReceiverWindowBufferSize uint32 `json:"sctp_max_receiver_window_buffer_size"`
	SctpDefaultStreamBufferedAmountLowThreshold uint32 `json:"sctp_default_stream_buffered_amount_low_threshold"`
	IsDataChannel bool `json:"is_data_channel"`
}

func (t *OptionsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	OptionsStart(builder)
	OptionsAddDirect(builder, t.Direct)
	if t.InitialAvailableOutgoingBitrate != nil {
		OptionsAddInitialAvailableOutgoingBitrate(builder, *t.InitialAvailableOutgoingBitrate)
	}
	OptionsAddEnableSctp(builder, t.EnableSctp)
	OptionsAddMaxSendMessageSize(builder, t.MaxSendMessageSize)
	OptionsAddMaxReceiveMessageSize(builder, t.MaxReceiveMessageSize)
	OptionsAddSctpSendBufferSize(builder, t.SctpSendBufferSize)
	OptionsAddSctpPerStreamSendQueueLimit(builder, t.SctpPerStreamSendQueueLimit)
	OptionsAddSctpMaxReceiverWindowBufferSize(builder, t.SctpMaxReceiverWindowBufferSize)
	OptionsAddSctpDefaultStreamBufferedAmountLowThreshold(builder, t.SctpDefaultStreamBufferedAmountLowThreshold)
	OptionsAddIsDataChannel(builder, t.IsDataChannel)
	return OptionsEnd(builder)
}

func (rcv *Options) UnPackTo(t *OptionsT) {
	t.Direct = rcv.Direct()
	t.InitialAvailableOutgoingBitrate = rcv.InitialAvailableOutgoingBitrate()
	t.EnableSctp = rcv.EnableSctp()
	t.MaxSendMessageSize = rcv.MaxSendMessageSize()
	t.MaxReceiveMessageSize = rcv.MaxReceiveMessageSize()
	t.SctpSendBufferSize = rcv.SctpSendBufferSize()
	t.SctpPerStreamSendQueueLimit = rcv.SctpPerStreamSendQueueLimit()
	t.SctpMaxReceiverWindowBufferSize = rcv.SctpMaxReceiverWindowBufferSize()
	t.SctpDefaultStreamBufferedAmountLowThreshold = rcv.SctpDefaultStreamBufferedAmountLowThreshold()
	t.IsDataChannel = rcv.IsDataChannel()
}

func (rcv *Options) UnPack() *OptionsT {
	if rcv == nil {
		return nil
	}
	t := &OptionsT{}
	rcv.UnPackTo(t)
	return t
}

type Options struct {
	_tab flatbuffers.Table
}

func GetRootAsOptions(buf []byte, offset flatbuffers.UOffsetT) *Options {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Options{}
	x.Init(buf, n+offset)
	return x
}

func FinishOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOptions(buf []byte, offset flatbuffers.UOffsetT) *Options {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Options{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Options) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Options) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Options) Direct() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Options) MutateDirect(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *Options) InitialAvailableOutgoingBitrate() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Options) MutateInitialAvailableOutgoingBitrate(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Options) EnableSctp() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Options) MutateEnableSctp(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *Options) MaxSendMessageSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateMaxSendMessageSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *Options) MaxReceiveMessageSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateMaxReceiveMessageSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *Options) SctpSendBufferSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateSctpSendBufferSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *Options) SctpPerStreamSendQueueLimit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateSctpPerStreamSendQueueLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *Options) SctpMaxReceiverWindowBufferSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateSctpMaxReceiverWindowBufferSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *Options) SctpDefaultStreamBufferedAmountLowThreshold() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Options) MutateSctpDefaultStreamBufferedAmountLowThreshold(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *Options) IsDataChannel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Options) MutateIsDataChannel(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func OptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func OptionsAddDirect(builder *flatbuffers.Builder, direct bool) {
	builder.PrependBoolSlot(0, direct, false)
}
func OptionsAddInitialAvailableOutgoingBitrate(builder *flatbuffers.Builder, initialAvailableOutgoingBitrate uint32) {
	builder.PrependUint32(initialAvailableOutgoingBitrate)
	builder.Slot(1)
}
func OptionsAddEnableSctp(builder *flatbuffers.Builder, enableSctp bool) {
	builder.PrependBoolSlot(2, enableSctp, false)
}
func OptionsAddMaxSendMessageSize(builder *flatbuffers.Builder, maxSendMessageSize uint32) {
	builder.PrependUint32Slot(3, maxSendMessageSize, 0)
}
func OptionsAddMaxReceiveMessageSize(builder *flatbuffers.Builder, maxReceiveMessageSize uint32) {
	builder.PrependUint32Slot(4, maxReceiveMessageSize, 0)
}
func OptionsAddSctpSendBufferSize(builder *flatbuffers.Builder, sctpSendBufferSize uint32) {
	builder.PrependUint32Slot(5, sctpSendBufferSize, 0)
}
func OptionsAddSctpPerStreamSendQueueLimit(builder *flatbuffers.Builder, sctpPerStreamSendQueueLimit uint32) {
	builder.PrependUint32Slot(6, sctpPerStreamSendQueueLimit, 0)
}
func OptionsAddSctpMaxReceiverWindowBufferSize(builder *flatbuffers.Builder, sctpMaxReceiverWindowBufferSize uint32) {
	builder.PrependUint32Slot(7, sctpMaxReceiverWindowBufferSize, 0)
}
func OptionsAddSctpDefaultStreamBufferedAmountLowThreshold(builder *flatbuffers.Builder, sctpDefaultStreamBufferedAmountLowThreshold uint32) {
	builder.PrependUint32Slot(8, sctpDefaultStreamBufferedAmountLowThreshold, 0)
}
func OptionsAddIsDataChannel(builder *flatbuffers.Builder, isDataChannel bool) {
	builder.PrependBoolSlot(9, isDataChannel, false)
}
func OptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
