// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__SctpAssociation "github.com/jiyeyuran/mediasoup-go/v2/internal/FBS/SctpAssociation"
)

type SctpNegotiatedCapabilitiesNotificationT struct {
	NegotiatedCapabilities *FBS__SctpAssociation.SctpNegotiatedCapabilitiesT `json:"negotiated_capabilities"`
}

func (t *SctpNegotiatedCapabilitiesNotificationT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	negotiatedCapabilitiesOffset := t.NegotiatedCapabilities.Pack(builder)
	SctpNegotiatedCapabilitiesNotificationStart(builder)
	SctpNegotiatedCapabilitiesNotificationAddNegotiatedCapabilities(builder, negotiatedCapabilitiesOffset)
	return SctpNegotiatedCapabilitiesNotificationEnd(builder)
}

func (rcv *SctpNegotiatedCapabilitiesNotification) UnPackTo(t *SctpNegotiatedCapabilitiesNotificationT) {
	t.NegotiatedCapabilities = rcv.NegotiatedCapabilities(nil).UnPack()
}

func (rcv *SctpNegotiatedCapabilitiesNotification) UnPack() *SctpNegotiatedCapabilitiesNotificationT {
	if rcv == nil {
		return nil
	}
	t := &SctpNegotiatedCapabilitiesNotificationT{}
	rcv.UnPackTo(t)
	return t
}

type SctpNegotiatedCapabilitiesNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsSctpNegotiatedCapabilitiesNotification(buf []byte, offset flatbuffers.UOffsetT) *SctpNegotiatedCapabilitiesNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SctpNegotiatedCapabilitiesNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishSctpNegotiatedCapabilitiesNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSctpNegotiatedCapabilitiesNotification(buf []byte, offset flatbuffers.UOffsetT) *SctpNegotiatedCapabilitiesNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SctpNegotiatedCapabilitiesNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSctpNegotiatedCapabilitiesNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SctpNegotiatedCapabilitiesNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SctpNegotiatedCapabilitiesNotification) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SctpNegotiatedCapabilitiesNotification) NegotiatedCapabilities(obj *FBS__SctpAssociation.SctpNegotiatedCapabilities) *FBS__SctpAssociation.SctpNegotiatedCapabilities {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__SctpAssociation.SctpNegotiatedCapabilities)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SctpNegotiatedCapabilitiesNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SctpNegotiatedCapabilitiesNotificationAddNegotiatedCapabilities(builder *flatbuffers.Builder, negotiatedCapabilities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(negotiatedCapabilities), 0)
}
func SctpNegotiatedCapabilitiesNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
