// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetMaxOutgoingBitrateRequestT struct {
	MaxOutgoingBitrate uint32 `json:"max_outgoing_bitrate"`
}

func (t *SetMaxOutgoingBitrateRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SetMaxOutgoingBitrateRequestStart(builder)
	SetMaxOutgoingBitrateRequestAddMaxOutgoingBitrate(builder, t.MaxOutgoingBitrate)
	return SetMaxOutgoingBitrateRequestEnd(builder)
}

func (rcv *SetMaxOutgoingBitrateRequest) UnPackTo(t *SetMaxOutgoingBitrateRequestT) {
	t.MaxOutgoingBitrate = rcv.MaxOutgoingBitrate()
}

func (rcv *SetMaxOutgoingBitrateRequest) UnPack() *SetMaxOutgoingBitrateRequestT {
	if rcv == nil {
		return nil
	}
	t := &SetMaxOutgoingBitrateRequestT{}
	rcv.UnPackTo(t)
	return t
}

type SetMaxOutgoingBitrateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSetMaxOutgoingBitrateRequest(buf []byte, offset flatbuffers.UOffsetT) *SetMaxOutgoingBitrateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetMaxOutgoingBitrateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetMaxOutgoingBitrateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetMaxOutgoingBitrateRequest(buf []byte, offset flatbuffers.UOffsetT) *SetMaxOutgoingBitrateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetMaxOutgoingBitrateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetMaxOutgoingBitrateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetMaxOutgoingBitrateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetMaxOutgoingBitrateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetMaxOutgoingBitrateRequest) MaxOutgoingBitrate() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SetMaxOutgoingBitrateRequest) MutateMaxOutgoingBitrate(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func SetMaxOutgoingBitrateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetMaxOutgoingBitrateRequestAddMaxOutgoingBitrate(builder *flatbuffers.Builder, maxOutgoingBitrate uint32) {
	builder.PrependUint32Slot(0, maxOutgoingBitrate, 0)
}
func SetMaxOutgoingBitrateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
