// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import "strconv"

type Method byte

const (
	MethodWORKER_DUMP                                    Method = 0
	MethodWORKER_GET_RESOURCE_USAGE                      Method = 1
	MethodWORKER_UPDATE_SETTINGS                         Method = 2
	MethodWORKER_CREATE_WEBRTCSERVER                     Method = 3
	MethodWORKER_CREATE_ROUTER                           Method = 4
	MethodWORKER_WEBRTCSERVER_CLOSE                      Method = 5
	MethodWORKER_CLOSE_ROUTER                            Method = 6
	MethodWEBRTCSERVER_DUMP                              Method = 7
	MethodROUTER_DUMP                                    Method = 8
	MethodROUTER_CREATE_WEBRTCTRANSPORT                  Method = 9
	MethodROUTER_CREATE_WEBRTCTRANSPORT_WITH_SERVER      Method = 10
	MethodROUTER_CREATE_PLAINTRANSPORT                   Method = 11
	MethodROUTER_CREATE_PIPETRANSPORT                    Method = 12
	MethodROUTER_CREATE_DIRECTTRANSPORT                  Method = 13
	MethodROUTER_CLOSE_TRANSPORT                         Method = 14
	MethodROUTER_CREATE_ACTIVESPEAKEROBSERVER            Method = 15
	MethodROUTER_CREATE_AUDIOLEVELOBSERVER               Method = 16
	MethodROUTER_CLOSE_RTPOBSERVER                       Method = 17
	MethodTRANSPORT_DUMP                                 Method = 18
	MethodTRANSPORT_GET_STATS                            Method = 19
	MethodTRANSPORT_CONNECT                              Method = 20
	MethodTRANSPORT_SET_MAX_INCOMING_BITRATE             Method = 21
	MethodTRANSPORT_SET_MAX_OUTGOING_BITRATE             Method = 22
	MethodTRANSPORT_SET_MIN_OUTGOING_BITRATE             Method = 23
	MethodTRANSPORT_RESTART_ICE                          Method = 24
	MethodTRANSPORT_PRODUCE                              Method = 25
	MethodTRANSPORT_PRODUCE_DATA                         Method = 26
	MethodTRANSPORT_CONSUME                              Method = 27
	MethodTRANSPORT_CONSUME_DATA                         Method = 28
	MethodTRANSPORT_ENABLE_TRACE_EVENT                   Method = 29
	MethodTRANSPORT_CLOSE_PRODUCER                       Method = 30
	MethodTRANSPORT_CLOSE_CONSUMER                       Method = 31
	MethodTRANSPORT_CLOSE_DATAPRODUCER                   Method = 32
	MethodTRANSPORT_CLOSE_DATACONSUMER                   Method = 33
	MethodPLAINTRANSPORT_CONNECT                         Method = 34
	MethodPIPETRANSPORT_CONNECT                          Method = 35
	MethodWEBRTCTRANSPORT_CONNECT                        Method = 36
	MethodPRODUCER_DUMP                                  Method = 37
	MethodPRODUCER_GET_STATS                             Method = 38
	MethodPRODUCER_PAUSE                                 Method = 39
	MethodPRODUCER_RESUME                                Method = 40
	MethodPRODUCER_ENABLE_TRACE_EVENT                    Method = 41
	MethodCONSUMER_DUMP                                  Method = 42
	MethodCONSUMER_GET_STATS                             Method = 43
	MethodCONSUMER_PAUSE                                 Method = 44
	MethodCONSUMER_RESUME                                Method = 45
	MethodCONSUMER_SET_PREFERRED_LAYERS                  Method = 46
	MethodCONSUMER_SET_PRIORITY                          Method = 47
	MethodCONSUMER_REQUEST_KEY_FRAME                     Method = 48
	MethodCONSUMER_ENABLE_TRACE_EVENT                    Method = 49
	MethodDATAPRODUCER_DUMP                              Method = 50
	MethodDATAPRODUCER_GET_STATS                         Method = 51
	MethodDATAPRODUCER_PAUSE                             Method = 52
	MethodDATAPRODUCER_RESUME                            Method = 53
	MethodDATACONSUMER_DUMP                              Method = 54
	MethodDATACONSUMER_GET_STATS                         Method = 55
	MethodDATACONSUMER_PAUSE                             Method = 56
	MethodDATACONSUMER_RESUME                            Method = 57
	MethodDATACONSUMER_GET_BUFFERED_AMOUNT               Method = 58
	MethodDATACONSUMER_SET_BUFFERED_AMOUNT_LOW_THRESHOLD Method = 59
	MethodDATACONSUMER_SEND                              Method = 60
	MethodDATACONSUMER_SET_SUBCHANNELS                   Method = 61
	MethodDATACONSUMER_ADD_SUBCHANNEL                    Method = 62
	MethodDATACONSUMER_REMOVE_SUBCHANNEL                 Method = 63
	MethodRTPOBSERVER_PAUSE                              Method = 64
	MethodRTPOBSERVER_RESUME                             Method = 65
	MethodRTPOBSERVER_ADD_PRODUCER                       Method = 66
	MethodRTPOBSERVER_REMOVE_PRODUCER                    Method = 67
)

var EnumNamesMethod = map[Method]string{
	MethodWORKER_DUMP:                                    "WORKER_DUMP",
	MethodWORKER_GET_RESOURCE_USAGE:                      "WORKER_GET_RESOURCE_USAGE",
	MethodWORKER_UPDATE_SETTINGS:                         "WORKER_UPDATE_SETTINGS",
	MethodWORKER_CREATE_WEBRTCSERVER:                     "WORKER_CREATE_WEBRTCSERVER",
	MethodWORKER_CREATE_ROUTER:                           "WORKER_CREATE_ROUTER",
	MethodWORKER_WEBRTCSERVER_CLOSE:                      "WORKER_WEBRTCSERVER_CLOSE",
	MethodWORKER_CLOSE_ROUTER:                            "WORKER_CLOSE_ROUTER",
	MethodWEBRTCSERVER_DUMP:                              "WEBRTCSERVER_DUMP",
	MethodROUTER_DUMP:                                    "ROUTER_DUMP",
	MethodROUTER_CREATE_WEBRTCTRANSPORT:                  "ROUTER_CREATE_WEBRTCTRANSPORT",
	MethodROUTER_CREATE_WEBRTCTRANSPORT_WITH_SERVER:      "ROUTER_CREATE_WEBRTCTRANSPORT_WITH_SERVER",
	MethodROUTER_CREATE_PLAINTRANSPORT:                   "ROUTER_CREATE_PLAINTRANSPORT",
	MethodROUTER_CREATE_PIPETRANSPORT:                    "ROUTER_CREATE_PIPETRANSPORT",
	MethodROUTER_CREATE_DIRECTTRANSPORT:                  "ROUTER_CREATE_DIRECTTRANSPORT",
	MethodROUTER_CLOSE_TRANSPORT:                         "ROUTER_CLOSE_TRANSPORT",
	MethodROUTER_CREATE_ACTIVESPEAKEROBSERVER:            "ROUTER_CREATE_ACTIVESPEAKEROBSERVER",
	MethodROUTER_CREATE_AUDIOLEVELOBSERVER:               "ROUTER_CREATE_AUDIOLEVELOBSERVER",
	MethodROUTER_CLOSE_RTPOBSERVER:                       "ROUTER_CLOSE_RTPOBSERVER",
	MethodTRANSPORT_DUMP:                                 "TRANSPORT_DUMP",
	MethodTRANSPORT_GET_STATS:                            "TRANSPORT_GET_STATS",
	MethodTRANSPORT_CONNECT:                              "TRANSPORT_CONNECT",
	MethodTRANSPORT_SET_MAX_INCOMING_BITRATE:             "TRANSPORT_SET_MAX_INCOMING_BITRATE",
	MethodTRANSPORT_SET_MAX_OUTGOING_BITRATE:             "TRANSPORT_SET_MAX_OUTGOING_BITRATE",
	MethodTRANSPORT_SET_MIN_OUTGOING_BITRATE:             "TRANSPORT_SET_MIN_OUTGOING_BITRATE",
	MethodTRANSPORT_RESTART_ICE:                          "TRANSPORT_RESTART_ICE",
	MethodTRANSPORT_PRODUCE:                              "TRANSPORT_PRODUCE",
	MethodTRANSPORT_PRODUCE_DATA:                         "TRANSPORT_PRODUCE_DATA",
	MethodTRANSPORT_CONSUME:                              "TRANSPORT_CONSUME",
	MethodTRANSPORT_CONSUME_DATA:                         "TRANSPORT_CONSUME_DATA",
	MethodTRANSPORT_ENABLE_TRACE_EVENT:                   "TRANSPORT_ENABLE_TRACE_EVENT",
	MethodTRANSPORT_CLOSE_PRODUCER:                       "TRANSPORT_CLOSE_PRODUCER",
	MethodTRANSPORT_CLOSE_CONSUMER:                       "TRANSPORT_CLOSE_CONSUMER",
	MethodTRANSPORT_CLOSE_DATAPRODUCER:                   "TRANSPORT_CLOSE_DATAPRODUCER",
	MethodTRANSPORT_CLOSE_DATACONSUMER:                   "TRANSPORT_CLOSE_DATACONSUMER",
	MethodPLAINTRANSPORT_CONNECT:                         "PLAINTRANSPORT_CONNECT",
	MethodPIPETRANSPORT_CONNECT:                          "PIPETRANSPORT_CONNECT",
	MethodWEBRTCTRANSPORT_CONNECT:                        "WEBRTCTRANSPORT_CONNECT",
	MethodPRODUCER_DUMP:                                  "PRODUCER_DUMP",
	MethodPRODUCER_GET_STATS:                             "PRODUCER_GET_STATS",
	MethodPRODUCER_PAUSE:                                 "PRODUCER_PAUSE",
	MethodPRODUCER_RESUME:                                "PRODUCER_RESUME",
	MethodPRODUCER_ENABLE_TRACE_EVENT:                    "PRODUCER_ENABLE_TRACE_EVENT",
	MethodCONSUMER_DUMP:                                  "CONSUMER_DUMP",
	MethodCONSUMER_GET_STATS:                             "CONSUMER_GET_STATS",
	MethodCONSUMER_PAUSE:                                 "CONSUMER_PAUSE",
	MethodCONSUMER_RESUME:                                "CONSUMER_RESUME",
	MethodCONSUMER_SET_PREFERRED_LAYERS:                  "CONSUMER_SET_PREFERRED_LAYERS",
	MethodCONSUMER_SET_PRIORITY:                          "CONSUMER_SET_PRIORITY",
	MethodCONSUMER_REQUEST_KEY_FRAME:                     "CONSUMER_REQUEST_KEY_FRAME",
	MethodCONSUMER_ENABLE_TRACE_EVENT:                    "CONSUMER_ENABLE_TRACE_EVENT",
	MethodDATAPRODUCER_DUMP:                              "DATAPRODUCER_DUMP",
	MethodDATAPRODUCER_GET_STATS:                         "DATAPRODUCER_GET_STATS",
	MethodDATAPRODUCER_PAUSE:                             "DATAPRODUCER_PAUSE",
	MethodDATAPRODUCER_RESUME:                            "DATAPRODUCER_RESUME",
	MethodDATACONSUMER_DUMP:                              "DATACONSUMER_DUMP",
	MethodDATACONSUMER_GET_STATS:                         "DATACONSUMER_GET_STATS",
	MethodDATACONSUMER_PAUSE:                             "DATACONSUMER_PAUSE",
	MethodDATACONSUMER_RESUME:                            "DATACONSUMER_RESUME",
	MethodDATACONSUMER_GET_BUFFERED_AMOUNT:               "DATACONSUMER_GET_BUFFERED_AMOUNT",
	MethodDATACONSUMER_SET_BUFFERED_AMOUNT_LOW_THRESHOLD: "DATACONSUMER_SET_BUFFERED_AMOUNT_LOW_THRESHOLD",
	MethodDATACONSUMER_SEND:                              "DATACONSUMER_SEND",
	MethodDATACONSUMER_SET_SUBCHANNELS:                   "DATACONSUMER_SET_SUBCHANNELS",
	MethodDATACONSUMER_ADD_SUBCHANNEL:                    "DATACONSUMER_ADD_SUBCHANNEL",
	MethodDATACONSUMER_REMOVE_SUBCHANNEL:                 "DATACONSUMER_REMOVE_SUBCHANNEL",
	MethodRTPOBSERVER_PAUSE:                              "RTPOBSERVER_PAUSE",
	MethodRTPOBSERVER_RESUME:                             "RTPOBSERVER_RESUME",
	MethodRTPOBSERVER_ADD_PRODUCER:                       "RTPOBSERVER_ADD_PRODUCER",
	MethodRTPOBSERVER_REMOVE_PRODUCER:                    "RTPOBSERVER_REMOVE_PRODUCER",
}

var EnumValuesMethod = map[string]Method{
	"WORKER_DUMP":                                    MethodWORKER_DUMP,
	"WORKER_GET_RESOURCE_USAGE":                      MethodWORKER_GET_RESOURCE_USAGE,
	"WORKER_UPDATE_SETTINGS":                         MethodWORKER_UPDATE_SETTINGS,
	"WORKER_CREATE_WEBRTCSERVER":                     MethodWORKER_CREATE_WEBRTCSERVER,
	"WORKER_CREATE_ROUTER":                           MethodWORKER_CREATE_ROUTER,
	"WORKER_WEBRTCSERVER_CLOSE":                      MethodWORKER_WEBRTCSERVER_CLOSE,
	"WORKER_CLOSE_ROUTER":                            MethodWORKER_CLOSE_ROUTER,
	"WEBRTCSERVER_DUMP":                              MethodWEBRTCSERVER_DUMP,
	"ROUTER_DUMP":                                    MethodROUTER_DUMP,
	"ROUTER_CREATE_WEBRTCTRANSPORT":                  MethodROUTER_CREATE_WEBRTCTRANSPORT,
	"ROUTER_CREATE_WEBRTCTRANSPORT_WITH_SERVER":      MethodROUTER_CREATE_WEBRTCTRANSPORT_WITH_SERVER,
	"ROUTER_CREATE_PLAINTRANSPORT":                   MethodROUTER_CREATE_PLAINTRANSPORT,
	"ROUTER_CREATE_PIPETRANSPORT":                    MethodROUTER_CREATE_PIPETRANSPORT,
	"ROUTER_CREATE_DIRECTTRANSPORT":                  MethodROUTER_CREATE_DIRECTTRANSPORT,
	"ROUTER_CLOSE_TRANSPORT":                         MethodROUTER_CLOSE_TRANSPORT,
	"ROUTER_CREATE_ACTIVESPEAKEROBSERVER":            MethodROUTER_CREATE_ACTIVESPEAKEROBSERVER,
	"ROUTER_CREATE_AUDIOLEVELOBSERVER":               MethodROUTER_CREATE_AUDIOLEVELOBSERVER,
	"ROUTER_CLOSE_RTPOBSERVER":                       MethodROUTER_CLOSE_RTPOBSERVER,
	"TRANSPORT_DUMP":                                 MethodTRANSPORT_DUMP,
	"TRANSPORT_GET_STATS":                            MethodTRANSPORT_GET_STATS,
	"TRANSPORT_CONNECT":                              MethodTRANSPORT_CONNECT,
	"TRANSPORT_SET_MAX_INCOMING_BITRATE":             MethodTRANSPORT_SET_MAX_INCOMING_BITRATE,
	"TRANSPORT_SET_MAX_OUTGOING_BITRATE":             MethodTRANSPORT_SET_MAX_OUTGOING_BITRATE,
	"TRANSPORT_SET_MIN_OUTGOING_BITRATE":             MethodTRANSPORT_SET_MIN_OUTGOING_BITRATE,
	"TRANSPORT_RESTART_ICE":                          MethodTRANSPORT_RESTART_ICE,
	"TRANSPORT_PRODUCE":                              MethodTRANSPORT_PRODUCE,
	"TRANSPORT_PRODUCE_DATA":                         MethodTRANSPORT_PRODUCE_DATA,
	"TRANSPORT_CONSUME":                              MethodTRANSPORT_CONSUME,
	"TRANSPORT_CONSUME_DATA":                         MethodTRANSPORT_CONSUME_DATA,
	"TRANSPORT_ENABLE_TRACE_EVENT":                   MethodTRANSPORT_ENABLE_TRACE_EVENT,
	"TRANSPORT_CLOSE_PRODUCER":                       MethodTRANSPORT_CLOSE_PRODUCER,
	"TRANSPORT_CLOSE_CONSUMER":                       MethodTRANSPORT_CLOSE_CONSUMER,
	"TRANSPORT_CLOSE_DATAPRODUCER":                   MethodTRANSPORT_CLOSE_DATAPRODUCER,
	"TRANSPORT_CLOSE_DATACONSUMER":                   MethodTRANSPORT_CLOSE_DATACONSUMER,
	"PLAINTRANSPORT_CONNECT":                         MethodPLAINTRANSPORT_CONNECT,
	"PIPETRANSPORT_CONNECT":                          MethodPIPETRANSPORT_CONNECT,
	"WEBRTCTRANSPORT_CONNECT":                        MethodWEBRTCTRANSPORT_CONNECT,
	"PRODUCER_DUMP":                                  MethodPRODUCER_DUMP,
	"PRODUCER_GET_STATS":                             MethodPRODUCER_GET_STATS,
	"PRODUCER_PAUSE":                                 MethodPRODUCER_PAUSE,
	"PRODUCER_RESUME":                                MethodPRODUCER_RESUME,
	"PRODUCER_ENABLE_TRACE_EVENT":                    MethodPRODUCER_ENABLE_TRACE_EVENT,
	"CONSUMER_DUMP":                                  MethodCONSUMER_DUMP,
	"CONSUMER_GET_STATS":                             MethodCONSUMER_GET_STATS,
	"CONSUMER_PAUSE":                                 MethodCONSUMER_PAUSE,
	"CONSUMER_RESUME":                                MethodCONSUMER_RESUME,
	"CONSUMER_SET_PREFERRED_LAYERS":                  MethodCONSUMER_SET_PREFERRED_LAYERS,
	"CONSUMER_SET_PRIORITY":                          MethodCONSUMER_SET_PRIORITY,
	"CONSUMER_REQUEST_KEY_FRAME":                     MethodCONSUMER_REQUEST_KEY_FRAME,
	"CONSUMER_ENABLE_TRACE_EVENT":                    MethodCONSUMER_ENABLE_TRACE_EVENT,
	"DATAPRODUCER_DUMP":                              MethodDATAPRODUCER_DUMP,
	"DATAPRODUCER_GET_STATS":                         MethodDATAPRODUCER_GET_STATS,
	"DATAPRODUCER_PAUSE":                             MethodDATAPRODUCER_PAUSE,
	"DATAPRODUCER_RESUME":                            MethodDATAPRODUCER_RESUME,
	"DATACONSUMER_DUMP":                              MethodDATACONSUMER_DUMP,
	"DATACONSUMER_GET_STATS":                         MethodDATACONSUMER_GET_STATS,
	"DATACONSUMER_PAUSE":                             MethodDATACONSUMER_PAUSE,
	"DATACONSUMER_RESUME":                            MethodDATACONSUMER_RESUME,
	"DATACONSUMER_GET_BUFFERED_AMOUNT":               MethodDATACONSUMER_GET_BUFFERED_AMOUNT,
	"DATACONSUMER_SET_BUFFERED_AMOUNT_LOW_THRESHOLD": MethodDATACONSUMER_SET_BUFFERED_AMOUNT_LOW_THRESHOLD,
	"DATACONSUMER_SEND":                              MethodDATACONSUMER_SEND,
	"DATACONSUMER_SET_SUBCHANNELS":                   MethodDATACONSUMER_SET_SUBCHANNELS,
	"DATACONSUMER_ADD_SUBCHANNEL":                    MethodDATACONSUMER_ADD_SUBCHANNEL,
	"DATACONSUMER_REMOVE_SUBCHANNEL":                 MethodDATACONSUMER_REMOVE_SUBCHANNEL,
	"RTPOBSERVER_PAUSE":                              MethodRTPOBSERVER_PAUSE,
	"RTPOBSERVER_RESUME":                             MethodRTPOBSERVER_RESUME,
	"RTPOBSERVER_ADD_PRODUCER":                       MethodRTPOBSERVER_ADD_PRODUCER,
	"RTPOBSERVER_REMOVE_PRODUCER":                    MethodRTPOBSERVER_REMOVE_PRODUCER,
}

func (v Method) String() string {
	if s, ok := EnumNamesMethod[v]; ok {
		return s
	}
	return "Method(" + strconv.FormatInt(int64(v), 10) + ")"
}
