// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpObserver

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddProducerRequestT struct {
	ProducerId string `json:"producer_id"`
}

func (t *AddProducerRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	producerIdOffset := flatbuffers.UOffsetT(0)
	if t.ProducerId != "" {
		producerIdOffset = builder.CreateString(t.ProducerId)
	}
	AddProducerRequestStart(builder)
	AddProducerRequestAddProducerId(builder, producerIdOffset)
	return AddProducerRequestEnd(builder)
}

func (rcv *AddProducerRequest) UnPackTo(t *AddProducerRequestT) {
	t.ProducerId = string(rcv.ProducerId())
}

func (rcv *AddProducerRequest) UnPack() *AddProducerRequestT {
	if rcv == nil {
		return nil
	}
	t := &AddProducerRequestT{}
	rcv.UnPackTo(t)
	return t
}

type AddProducerRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAddProducerRequest(buf []byte, offset flatbuffers.UOffsetT) *AddProducerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddProducerRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddProducerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddProducerRequest(buf []byte, offset flatbuffers.UOffsetT) *AddProducerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddProducerRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddProducerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddProducerRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddProducerRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddProducerRequest) ProducerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AddProducerRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AddProducerRequestAddProducerId(builder *flatbuffers.Builder, producerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(producerId), 0)
}
func AddProducerRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
