// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SctpAssociation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SctpNegotiatedCapabilitiesT struct {
	NegotiatedMaxOutboundStreams uint16 `json:"negotiated_max_outbound_streams"`
	NegotiatedMaxInboundStreams uint16 `json:"negotiated_max_inbound_streams"`
}

func (t *SctpNegotiatedCapabilitiesT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SctpNegotiatedCapabilitiesStart(builder)
	SctpNegotiatedCapabilitiesAddNegotiatedMaxOutboundStreams(builder, t.NegotiatedMaxOutboundStreams)
	SctpNegotiatedCapabilitiesAddNegotiatedMaxInboundStreams(builder, t.NegotiatedMaxInboundStreams)
	return SctpNegotiatedCapabilitiesEnd(builder)
}

func (rcv *SctpNegotiatedCapabilities) UnPackTo(t *SctpNegotiatedCapabilitiesT) {
	t.NegotiatedMaxOutboundStreams = rcv.NegotiatedMaxOutboundStreams()
	t.NegotiatedMaxInboundStreams = rcv.NegotiatedMaxInboundStreams()
}

func (rcv *SctpNegotiatedCapabilities) UnPack() *SctpNegotiatedCapabilitiesT {
	if rcv == nil {
		return nil
	}
	t := &SctpNegotiatedCapabilitiesT{}
	rcv.UnPackTo(t)
	return t
}

type SctpNegotiatedCapabilities struct {
	_tab flatbuffers.Table
}

func GetRootAsSctpNegotiatedCapabilities(buf []byte, offset flatbuffers.UOffsetT) *SctpNegotiatedCapabilities {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SctpNegotiatedCapabilities{}
	x.Init(buf, n+offset)
	return x
}

func FinishSctpNegotiatedCapabilitiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSctpNegotiatedCapabilities(buf []byte, offset flatbuffers.UOffsetT) *SctpNegotiatedCapabilities {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SctpNegotiatedCapabilities{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSctpNegotiatedCapabilitiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SctpNegotiatedCapabilities) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SctpNegotiatedCapabilities) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SctpNegotiatedCapabilities) NegotiatedMaxOutboundStreams() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpNegotiatedCapabilities) MutateNegotiatedMaxOutboundStreams(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *SctpNegotiatedCapabilities) NegotiatedMaxInboundStreams() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpNegotiatedCapabilities) MutateNegotiatedMaxInboundStreams(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func SctpNegotiatedCapabilitiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SctpNegotiatedCapabilitiesAddNegotiatedMaxOutboundStreams(builder *flatbuffers.Builder, negotiatedMaxOutboundStreams uint16) {
	builder.PrependUint16Slot(0, negotiatedMaxOutboundStreams, 0)
}
func SctpNegotiatedCapabilitiesAddNegotiatedMaxInboundStreams(builder *flatbuffers.Builder, negotiatedMaxInboundStreams uint16) {
	builder.PrependUint16Slot(1, negotiatedMaxInboundStreams, 0)
}
func SctpNegotiatedCapabilitiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
