// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SctpAssociation

import "strconv"

type SctpState byte

const (
	SctpStateNEW        SctpState = 0
	SctpStateCONNECTING SctpState = 1
	SctpStateCONNECTED  SctpState = 2
	SctpStateFAILED     SctpState = 3
	SctpStateCLOSED     SctpState = 4
)

var EnumNamesSctpState = map[SctpState]string{
	SctpStateNEW:        "NEW",
	SctpStateCONNECTING: "CONNECTING",
	SctpStateCONNECTED:  "CONNECTED",
	SctpStateFAILED:     "FAILED",
	SctpStateCLOSED:     "CLOSED",
}

var EnumValuesSctpState = map[string]SctpState{
	"NEW":        SctpStateNEW,
	"CONNECTING": SctpStateCONNECTING,
	"CONNECTED":  SctpStateCONNECTED,
	"FAILED":     SctpStateFAILED,
	"CLOSED":     SctpStateCLOSED,
}

func (v SctpState) String() string {
	if s, ok := EnumNamesSctpState[v]; ok {
		return s
	}
	return "SctpState(" + strconv.FormatInt(int64(v), 10) + ")"
}
