// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SctpParameters

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SctpParametersT struct {
	Port uint16 `json:"port"`
	MaxSendMessageSize uint32 `json:"max_send_message_size"`
	MaxReceiveMessageSize uint32 `json:"max_receive_message_size"`
	SendBufferSize uint32 `json:"send_buffer_size"`
	PerStreamSendQueueLimit uint32 `json:"per_stream_send_queue_limit"`
	MaxReceiverWindowBufferSize uint32 `json:"max_receiver_window_buffer_size"`
	IsDataChannel bool `json:"is_data_channel"`
}

func (t *SctpParametersT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SctpParametersStart(builder)
	SctpParametersAddPort(builder, t.Port)
	SctpParametersAddMaxSendMessageSize(builder, t.MaxSendMessageSize)
	SctpParametersAddMaxReceiveMessageSize(builder, t.MaxReceiveMessageSize)
	SctpParametersAddSendBufferSize(builder, t.SendBufferSize)
	SctpParametersAddPerStreamSendQueueLimit(builder, t.PerStreamSendQueueLimit)
	SctpParametersAddMaxReceiverWindowBufferSize(builder, t.MaxReceiverWindowBufferSize)
	SctpParametersAddIsDataChannel(builder, t.IsDataChannel)
	return SctpParametersEnd(builder)
}

func (rcv *SctpParameters) UnPackTo(t *SctpParametersT) {
	t.Port = rcv.Port()
	t.MaxSendMessageSize = rcv.MaxSendMessageSize()
	t.MaxReceiveMessageSize = rcv.MaxReceiveMessageSize()
	t.SendBufferSize = rcv.SendBufferSize()
	t.PerStreamSendQueueLimit = rcv.PerStreamSendQueueLimit()
	t.MaxReceiverWindowBufferSize = rcv.MaxReceiverWindowBufferSize()
	t.IsDataChannel = rcv.IsDataChannel()
}

func (rcv *SctpParameters) UnPack() *SctpParametersT {
	if rcv == nil {
		return nil
	}
	t := &SctpParametersT{}
	rcv.UnPackTo(t)
	return t
}

type SctpParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsSctpParameters(buf []byte, offset flatbuffers.UOffsetT) *SctpParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SctpParameters{}
	x.Init(buf, n+offset)
	return x
}

func FinishSctpParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSctpParameters(buf []byte, offset flatbuffers.UOffsetT) *SctpParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SctpParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSctpParametersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SctpParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SctpParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SctpParameters) Port() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutatePort(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *SctpParameters) MaxSendMessageSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutateMaxSendMessageSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SctpParameters) MaxReceiveMessageSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutateMaxReceiveMessageSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *SctpParameters) SendBufferSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutateSendBufferSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *SctpParameters) PerStreamSendQueueLimit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutatePerStreamSendQueueLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *SctpParameters) MaxReceiverWindowBufferSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SctpParameters) MutateMaxReceiverWindowBufferSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *SctpParameters) IsDataChannel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SctpParameters) MutateIsDataChannel(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func SctpParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func SctpParametersAddPort(builder *flatbuffers.Builder, port uint16) {
	builder.PrependUint16Slot(0, port, 0)
}
func SctpParametersAddMaxSendMessageSize(builder *flatbuffers.Builder, maxSendMessageSize uint32) {
	builder.PrependUint32Slot(1, maxSendMessageSize, 0)
}
func SctpParametersAddMaxReceiveMessageSize(builder *flatbuffers.Builder, maxReceiveMessageSize uint32) {
	builder.PrependUint32Slot(2, maxReceiveMessageSize, 0)
}
func SctpParametersAddSendBufferSize(builder *flatbuffers.Builder, sendBufferSize uint32) {
	builder.PrependUint32Slot(3, sendBufferSize, 0)
}
func SctpParametersAddPerStreamSendQueueLimit(builder *flatbuffers.Builder, perStreamSendQueueLimit uint32) {
	builder.PrependUint32Slot(4, perStreamSendQueueLimit, 0)
}
func SctpParametersAddMaxReceiverWindowBufferSize(builder *flatbuffers.Builder, maxReceiverWindowBufferSize uint32) {
	builder.PrependUint32Slot(5, maxReceiverWindowBufferSize, 0)
}
func SctpParametersAddIsDataChannel(builder *flatbuffers.Builder, isDataChannel bool) {
	builder.PrependBoolSlot(6, isDataChannel, false)
}
func SctpParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
