// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DataProducer

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__SctpParameters "github.com/jiyeyuran/mediasoup-go/internal/FBS/SctpParameters"
)

type DumpResponseT struct {
	Id string `json:"id"`
	Type Type `json:"type"`
	SctpStreamParameters *FBS__SctpParameters.SctpStreamParametersT `json:"sctp_stream_parameters"`
	Label string `json:"label"`
	Protocol string `json:"protocol"`
	Paused bool `json:"paused"`
}

func (t *DumpResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	sctpStreamParametersOffset := t.SctpStreamParameters.Pack(builder)
	labelOffset := flatbuffers.UOffsetT(0)
	if t.Label != "" {
		labelOffset = builder.CreateString(t.Label)
	}
	protocolOffset := flatbuffers.UOffsetT(0)
	if t.Protocol != "" {
		protocolOffset = builder.CreateString(t.Protocol)
	}
	DumpResponseStart(builder)
	DumpResponseAddId(builder, idOffset)
	DumpResponseAddType(builder, t.Type)
	DumpResponseAddSctpStreamParameters(builder, sctpStreamParametersOffset)
	DumpResponseAddLabel(builder, labelOffset)
	DumpResponseAddProtocol(builder, protocolOffset)
	DumpResponseAddPaused(builder, t.Paused)
	return DumpResponseEnd(builder)
}

func (rcv *DumpResponse) UnPackTo(t *DumpResponseT) {
	t.Id = string(rcv.Id())
	t.Type = rcv.Type()
	t.SctpStreamParameters = rcv.SctpStreamParameters(nil).UnPack()
	t.Label = string(rcv.Label())
	t.Protocol = string(rcv.Protocol())
	t.Paused = rcv.Paused()
}

func (rcv *DumpResponse) UnPack() *DumpResponseT {
	if rcv == nil {
		return nil
	}
	t := &DumpResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DumpResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDumpResponse(buf []byte, offset flatbuffers.UOffsetT) *DumpResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DumpResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishDumpResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDumpResponse(buf []byte, offset flatbuffers.UOffsetT) *DumpResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DumpResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDumpResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DumpResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DumpResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DumpResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DumpResponse) Type() Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DumpResponse) MutateType(n Type) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *DumpResponse) SctpStreamParameters(obj *FBS__SctpParameters.SctpStreamParameters) *FBS__SctpParameters.SctpStreamParameters {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__SctpParameters.SctpStreamParameters)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DumpResponse) Label() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DumpResponse) Protocol() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DumpResponse) Paused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DumpResponse) MutatePaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func DumpResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func DumpResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DumpResponseAddType(builder *flatbuffers.Builder, type_ Type) {
	builder.PrependByteSlot(1, byte(type_), 0)
}
func DumpResponseAddSctpStreamParameters(builder *flatbuffers.Builder, sctpStreamParameters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sctpStreamParameters), 0)
}
func DumpResponseAddLabel(builder *flatbuffers.Builder, label flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(label), 0)
}
func DumpResponseAddProtocol(builder *flatbuffers.Builder, protocol flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(protocol), 0)
}
func DumpResponseAddPaused(builder *flatbuffers.Builder, paused bool) {
	builder.PrependBoolSlot(5, paused, false)
}
func DumpResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
