// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package DataProducer

import "strconv"

type Type byte

const (
	TypeSCTP   Type = 0
	TypeDIRECT Type = 1
)

var EnumNamesType = map[Type]string{
	TypeSCTP:   "SCTP",
	TypeDIRECT: "DIRECT",
}

var EnumValuesType = map[string]Type{
	"SCTP":   TypeSCTP,
	"DIRECT": TypeDIRECT,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
